Repository oat-sa/simple-roster, pull requests merged in 2020-12, with the labels that each got.

#177 [RO-65] Enabled BooleanArgumentFlag rule in phpmd.xml
  config/services.yaml
  phpmd.xml
  src/Responder/SerializerResponder.php
  tests/Integration/Responder/SerializerResponderTest.php
Labels: Type: CI

#173 [RO-79] Update Line Items via web hook
  .env
  .env.docker
  .env.test
  CHANGELOG.md
  README.md
  config/doctrine/Assignment.orm.xml
  config/doctrine/LineItem.orm.xml
  config/packages/security.yaml
  config/routes.yaml
  config/services.yaml
  config/services_test.yaml
  docs/cli/line-item-cache-warmer-command.md
  docs/features/update-line-items-webhook.md
  openapi/api_v1.yml
  src/Action/WebHook/UpdateLineItemsWebhookAction.php
  src/Command/Cache/LineItemCacheWarmerCommand.php
  src/Entity/Assignment.php
  src/EventListener/Doctrine/LineItemLoaderListener.php
  src/EventListener/Doctrine/WarmUpLineItemCacheListener.php
  src/Generator/LineItemCacheIdGenerator.php
  src/Repository/LineItemRepository.php
  src/Repository/UserRepository.php
  src/Request/ParamConverter/UpdateLineItemWebHookParamConverter.php
  src/Request/Validator/UpdateLineItemValidator.php
  src/WebHook/Service/UpdateLineItemsService.php
  src/WebHook/UpdateLineItemCollection.php
  src/WebHook/UpdateLineItemDto.php
  tests/Fixtures/3LineItems.yml
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Functional/Command/Cache/LineItemCacheWarmerCommandTest.php
  tests/Integration/Repository/LineItemRepositoryTest.php
  tests/Unit/Command/Cache/LineItemCacheWarmerCommandTest.php
  tests/Unit/EventListener/Doctrine/WarmUpLineItemCacheListenerTest.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
  tests/Unit/Request/Validator/UpdateLineItemValidatorTest.php
  tests/Unit/Webhook/Service/UpdateLineItemsServiceTest.php
  tests/Unit/Webhook/UpdateLineItemCollectionTest.php
Labels: Type: Feature

#174 [RO-60] Basic Outcome for LTI 1.3
  .env
  .env.docker
  .env.test
  CHANGELOG.md
  composer.json
  composer.lock
  config/bundles.php
  config/packages/docker/lti1p3.yaml
  config/packages/lti1p3.yaml
  config/packages/security.yaml
  config/packages/test/lti1p3.yaml
  config/routes.yaml
  config/services_test.yaml
  docker-compose.yml
  docs/devops-documentation.md
  openapi/api_v1.yml
  src/Action/Lti/UpdateLti1p1OutcomeAction.php
  src/Action/Lti/UpdateLti1p3OutcomeAction.php
  src/Entity/Assignment.php
  src/Lti/Builder/Lti1p1LaunchUrlBuilder.php
  src/Lti/Builder/Lti1p3MessageBuilder.php
  src/Lti/Factory/Lti1p3RequestFactory.php
  src/Lti/Responder/LtiOutcomeResponder.php
  src/Lti/Responder/XmlResponse.php
  templates/basic-outcome/replace-result-response.xml.twig
  tests/Functional/Action/Lti/GetUserAssignmentLtiLinkActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p1OutcomeActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p3OutcomeActionTest.php
  tests/Integration/Lti/Builder/Lti1p3MessageBuilderTest.php
  tests/Integration/Lti/Responder/LtiOutcomeResponderTest.php
  tests/Resources/LtiOutcome/invalid_replace_result_body_missing_id.xml
  tests/Resources/LtiOutcome/invalid_replace_result_body_wrong_assignment.xml
  tests/Resources/LtiOutcome/invalid_replace_result_body_wrong_namespace.xml
  tests/Resources/LtiOutcome/valid_replace_result_body.xml
  tests/Resources/LtiOutcome/valid_replace_result_body_with_old_namespace.xml
  tests/Traits/AssignmentStatusTestingTrait.php
  tests/Traits/XmlTestingTrait.php
  tests/Unit/EventListener/Doctrine/LineItemLoaderListenerTest.php
  tests/Unit/Lti/Extractor/ReplaceResultSourceIdExtractorTest.php
  tests/Unit/Lti/Factory/Lti1p3RequestFactoryTest.php
  tests/Unit/Lti/Responder/XmlResponseTest.php
  tests/Unit/Security/Lti/OidcUserAuthenticatorTest.php
Labels: Type: Bugfix, Type: Feature

#179 [RO-94] Command for changing start end dates on line_item(s)
  CHANGELOG.md
  README.md
  docs/cli/modify-entity-line-item-change-dates-command.md
  docs/cli/modify-entity-line-item-change-state-command.md
  infection.json
  src/Command/ModifyEntity/LineItem/LineItemChangeDatesCommand.php
  src/Entity/LineItem.php
  src/Repository/Criteria/FindLineItemCriteria.php
  src/Repository/LineItemRepository.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeDatesCommandTest.php
  tests/Integration/Repository/LineItemRepositoryTest.php
  tests/Unit/Repository/Criteria/FindLineItemCriteriaTest.php
Labels: Type: Feature
