Repository oat-sa/simple-roster, pull requests merged in 2021-03, with the labels that each got.

#198 [AUT-16] Tao webhook - rename deliveryURI to remoteDeliveryId
  CHANGELOG.md
  docs/features/update-line-items-webhook.md
  openapi/api_v1.yml
  src/Request/ParamConverter/UpdateLineItemWebHookParamConverter.php
  src/Request/Validator/UpdateLineItemValidator.php
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
Labels: Type: Bugfix

#200 Release v2.0.5
  CHANGELOG.md
  README.md
  docs/features/update-line-items-webhook.md
  openapi/api_v1.yml
  src/Request/ParamConverter/UpdateLineItemWebHookParamConverter.php
  src/Request/Validator/UpdateLineItemValidator.php
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
Labels: Type: Release

#204 [RO-224] Consider timezone on update dates command
  CHANGELOG.md
  docs/cli/modify-entity-line-item-change-dates-command.md
  src/Command/ModifyEntity/LineItem/LineItemChangeDatesCommand.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeDatesCommandTest.php
Labels: Type: Bugfix

#202 [RO-238] Tao webhook - rename event name value
  CHANGELOG.md
  docs/features/update-line-items-webhook.md
  src/WebHook/UpdateLineItemDto.php
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
  tests/Unit/Webhook/Service/UpdateLineItemsServiceTest.php
Labels: Type: Bugfix

#207 Release 2.0.6
  CHANGELOG.md
  README.md
  docs/cli/modify-entity-line-item-change-dates-command.md
  docs/features/update-line-items-webhook.md
  src/Command/ModifyEntity/LineItem/LineItemChangeDatesCommand.php
  src/WebHook/UpdateLineItemDto.php
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeDatesCommandTest.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
  tests/Unit/Webhook/Service/UpdateLineItemsServiceTest.php
Labels: Type: Release

#203 [RO-269] UUID identifier generation strategy for LTI instances
  CHANGELOG.md
  composer.json
  composer.lock
  config/doctrine/LtiInstance.orm.xml
  phpmd.xml
  src/Command/Ingester/LtiInstanceIngesterCommand.php
  src/Entity/EntityInterface.php
  src/Entity/LtiInstance.php
  src/EventSubscriber/OAuthSignatureValidationSubscriber.php
  src/EventSubscriber/RequestIdGeneratorSubscriber.php
  src/Faker/Provider/UuidFakerProvider.php
  src/Logger/UserRequestLogProcessor.php
  src/Request/RequestIdStorage.php
  src/Service/CompleteUserAssignmentService.php
  symfony.lock
  tests/Fixtures/5ltiInstances.yml
  tests/Fixtures/userWithReadyAssignment.yml
  tests/Functional/Action/Lti/UpdateLti1p1OutcomeActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p3OutcomeActionTest.php
  tests/Integration/Lti/Responder/LtiOutcomeResponderTest.php
  tests/Integration/Repository/LtiInstanceRepositoryTest.php
  tests/Traits/XmlTestingTrait.php
  tests/Unit/Entity/LtiInstanceTest.php
  tests/Unit/EventSubscriber/RequestIdGeneratorSubscriberTest.php
  tests/Unit/Faker/Provider/UuidFakerProviderTest.php
  tests/Unit/Logger/UserRequestLogProcessorTest.php
  tests/Unit/Lti/Builder/Lti1p1LaunchUrlBuilderTest.php
  tests/Unit/Lti/Collection/UniqueLtiInstanceCollectionTest.php
  tests/Unit/Lti/Factory/Lti1p1RequestFactoryTest.php
  tests/Unit/Lti/LoadBalancer/UserGroupIdLtiInstanceLoadBalancerTest.php
  tests/Unit/Lti/LoadBalancer/UsernameLtiInstanceLoadBalancerTest.php
Labels: Type: Feature

#205 [RO-269] UUID identifier generation strategy for Line items
  config/doctrine/Assignment.orm.xml
  config/doctrine/LineItem.orm.xml
  docs/cli/modify-entity-line-item-change-dates-command.md
  docs/cli/modify-entity-line-item-change-state-command.md
  src/Command/Cache/LineItemCacheWarmerCommand.php
  src/Command/Ingester/AssignmentIngesterCommand.php
  src/Command/Ingester/LineItemIngesterCommand.php
  src/Command/ModifyEntity/LineItem/LineItemChangeDatesCommand.php
  src/Command/ModifyEntity/LineItem/LineItemChangeStateCommand.php
  src/DataTransferObject/AssignmentDto.php
  src/Entity/Assignment.php
  src/Entity/LineItem.php
  src/EventListener/Doctrine/LineItemLoaderListener.php
  src/EventListener/Doctrine/WarmUpLineItemCacheListener.php
  src/Generator/LineItemCacheIdGenerator.php
  src/Repository/Criteria/FindLineItemCriteria.php
  src/Repository/LineItemRepository.php
  src/Repository/NativeAssignmentRepository.php
  src/WebHook/Service/UpdateLineItemsService.php
  tests/Fixtures/100usersWithAssignments.yml
  tests/Fixtures/3LineItems.yml
  tests/Fixtures/userWithReadyAssignment.yml
  tests/Fixtures/usersWithStartedButStuckAssignments.yml
  tests/Functional/Action/Lti/GetUserAssignmentLtiLinkActionTest.php
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Functional/Command/Cache/LineItemCacheWarmerCommandTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeDatesCommandTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeStateCommandTest.php
  tests/Integration/Repository/LineItemRepositoryTest.php
  tests/Integration/Repository/NativeAssignmentRepositoryTest.php
  tests/Unit/DataTransferObject/AssignmentDtoCollectionTest.php
  tests/Unit/EventListener/Doctrine/LineItemLoaderListenerTest.php
  tests/Unit/EventListener/Doctrine/WarmUpLineItemCacheListenerTest.php
  tests/Unit/Ingester/AssignmentIngesterTest.php
  tests/Unit/Lti/Collection/UniqueLtiInstanceCollectionTest.php
  tests/Unit/Lti/LoadBalancer/UsernameLtiInstanceLoadBalancerTest.php
  tests/Unit/Repository/Criteria/FindLineItemCriteriaTest.php
  tests/Unit/Webhook/Service/UpdateLineItemsServiceTest.php
Labels: Type: Feature

#208 [RO-269] UUID identifier generation strategy for Assignments
  config/doctrine/Assignment.orm.xml
  openapi/api_v1.yml
  src/Action/Lti/GetUserAssignmentLtiLinkAction.php
  src/Command/Ingester/AssignmentIngesterCommand.php
  src/Command/ModifyEntity/LineItem/LineItemChangeDatesCommand.php
  src/Command/ModifyEntity/LineItem/LineItemChangeStateCommand.php
  src/DataTransferObject/AssignmentDto.php
  src/DataTransferObject/LoginHintDto.php
  src/Entity/Assignment.php
  src/Entity/User.php
  src/Exception/AssignmentNotProcessableException.php
  src/Ingester/AssignmentIngester.php
  src/Lti/Builder/Lti1p1LaunchUrlBuilder.php
  src/Lti/Builder/Lti1p3MessageBuilder.php
  src/Lti/Extractor/LoginHintExtractor.php
  src/Lti/Extractor/ReplaceResultSourceIdExtractor.php
  src/Lti/Responder/LtiOutcomeResponder.php
  src/Lti/Service/GetUserAssignmentLtiRequestService.php
  src/Repository/AssignmentRepository.php
  src/Repository/NativeAssignmentRepository.php
  src/Security/Lti/OidcUserAuthenticator.php
  src/Service/CompleteUserAssignmentService.php
  src/WebHook/Service/UpdateLineItemsService.php
  tests/Fixtures/userWithAllAttemptsTaken.yml
  tests/Fixtures/userWithReadyAssignment.yml
  tests/Fixtures/userWithUnavailableAssignment.yml
  tests/Fixtures/usersWithStartedButStuckAssignments.yml
  tests/Functional/Action/Assignment/ListUserAssignmentsActionTest.php
  tests/Functional/Action/Bulk/BulkUpdateUsersAssignmentsStateActionTest.php
  tests/Functional/Action/Lti/GetUserAssignmentLtiLinkActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p1OutcomeActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p3OutcomeActionTest.php
  tests/Functional/Command/GarbageCollector/AssignmentGarbageCollectorCommandTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeDatesCommandTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeStateCommandTest.php
  tests/Integration/Entity/UserTest.php
  tests/Integration/Lti/Builder/Lti1p3MessageBuilderTest.php
  tests/Integration/Lti/Responder/LtiOutcomeResponderTest.php
  tests/Integration/Repository/AssignmentRepositoryTest.php
  tests/Integration/Repository/NativeAssignmentRepositoryTest.php
  tests/Traits/AssignmentStatusTestingTrait.php
  tests/Traits/XmlTestingTrait.php
  tests/Unit/DataTransferObject/AssignmentDtoCollectionTest.php
  tests/Unit/DataTransferObject/LoginHintDtoTest.php
  tests/Unit/Ingester/AssignmentIngesterTest.php
  tests/Unit/Lti/Builder/Lti1p1LaunchUrlBuilderTest.php
  tests/Unit/Lti/Extractor/LoginHintExtractorTest.php
  tests/Unit/Lti/Extractor/ReplaceResultSourceIdExtractorTest.php
  tests/Unit/Lti/Factory/Lti1p3RequestFactoryTest.php
  tests/Unit/Lti/Service/GetUserAssignmentLtiRequestServiceTest.php
  tests/Unit/Security/Lti/OidcUserAuthenticatorTest.php
  tests/Unit/Service/Bulk/BulkUpdateUsersAssignmentsStateServiceTest.php
  tests/Unit/Service/CompleteUserAssignmentServiceTest.php
Labels: Type: Feature

#209 [RO-269] UUID identifier generation strategy for Users
  CHANGELOG.md
  composer.lock
  config/doctrine/Assignment.orm.xml
  config/doctrine/User.orm.xml
  docs/cli/user-cache-warmer-command.md
  psalm.xml.dist
  src/Command/Cache/UserCacheWarmerCommand.php
  src/Command/Ingester/UserIngesterCommand.php
  src/DataTransferObject/AssignmentDto.php
  src/DataTransferObject/UserDto.php
  src/Entity/EntityInterface.php
  src/Entity/User.php
  src/Ingester/AssignmentIngester.php
  src/Repository/AssignmentRepository.php
  src/Repository/Criteria/EuclideanDivisionCriterion.php
  src/Repository/Criteria/FindUserCriteria.php
  src/Repository/NativeUserRepository.php
  src/Repository/UserRepository.php
  src/ResultSet/UsernameResultSet.php
  tests/Fixtures/userWithReadyAssignment.yml
  tests/Functional/Action/Assignment/ListUserAssignmentsActionTest.php
  tests/Functional/Action/Bulk/BulkCreateUsersAssignmentsActionTest.php
  tests/Functional/Action/Bulk/BulkUpdateUsersAssignmentsStateActionTest.php
  tests/Functional/Action/HealthCheck/HealthCheckActionTest.php
  tests/Functional/Action/Lti/GetUserAssignmentLtiLinkActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p1OutcomeActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p3OutcomeActionTest.php
  tests/Functional/Action/Security/LoginActionTest.php
  tests/Functional/Action/Security/LogoutActionTest.php
  tests/Functional/Action/Security/RefreshAccessTokenActionTest.php
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Functional/Command/Cache/UserCacheWarmerCommandTest.php
  tests/Functional/Command/Ingester/AssignmentIngesterCommandTest.php
  tests/Helpers/Authentication/AuthenticationResponse.php
  tests/Integration/Entity/UserTest.php
  tests/Integration/Lti/Builder/Lti1p3MessageBuilderTest.php
  tests/Integration/Lti/Responder/LtiOutcomeResponderTest.php
  tests/Integration/Repository/AssignmentRepositoryTest.php
  tests/Integration/Repository/NativeUserRepositoryTest.php
  tests/Integration/Repository/UserRepositoryTest.php
  tests/Integration/Responder/SerializerResponderTest.php
  tests/Integration/Security/Authenticator/JwtTokenAuthenticatorTest.php
  tests/Integration/Security/Generator/JwtTokenGeneratorTest.php
  tests/Integration/Security/Verifier/JwtTokenVerifierTest.php
  tests/Traits/ApiTestingTrait.php
  tests/Traits/AssignmentStatusTestingTrait.php
  tests/Traits/CsvIngestionTestingTrait.php
  tests/Traits/DatabaseTestingTrait.php
  tests/Traits/LoggerTestingTrait.php
  tests/Traits/UserAuthenticatorTrait.php
  tests/Unit/DataTransferObject/AssignmentDtoCollectionTest.php
  tests/Unit/DataTransferObject/UserDtoCollectionTest.php
  tests/Unit/DataTransferObject/UserDtoTest.php
  tests/Unit/Ingester/AssignmentIngesterTest.php
  tests/Unit/Lti/LoadBalancer/UserGroupIdLtiInstanceLoadBalancerTest.php
  tests/Unit/Repository/Criteria/EuclideanDivisionCriterionTest.php
  tests/Unit/Repository/Criteria/FindUserCriteriaTest.php
  tests/Unit/Security/Lti/OidcUserAuthenticatorTest.php
Labels: Type: Feature

#212 Fixed memory leak in user cache warmup process
  CHANGELOG.md
  README.md
  phpunit.xml.dist
  src/MessageHandler/WarmUpGroupedUserCacheMessageHandler.php
Labels: Type: Bugfix

#213 Release v2.0.7
  CHANGELOG.md
  README.md
  phpunit.xml.dist
  src/MessageHandler/WarmUpGroupedUserCacheMessageHandler.php
Labels: Type: Release
