Repository oat-sa/simple-roster, pull requests merged in 2021-04, with the labels that each got.

#216 [RO-357] Phpseclib security vulnerability fix
  .Jenkinsfile
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  config/services.yaml
  phpunit.xml.dist
  src/Command/Cache/UserCacheWarmerCommand.php
  src/Command/GarbageCollector/AssignmentGarbageCollectorCommand.php
  src/Command/Ingester/AbstractCsvIngesterCommand.php
  src/Security/Authenticator/JwtTokenAuthenticator.php
  src/Security/Generator/JwtTokenCacheIdGenerator.php
  src/Security/Generator/JwtTokenGenerator.php
  src/Security/Verifier/JwtTokenVerifier.php
  symfony.lock
  tests/Functional/Action/Lti/UpdateLti1p3OutcomeActionTest.php
  tests/Integration/Lti/Builder/Lti1p3MessageBuilderTest.php
  tests/Integration/Security/Authenticator/JwtTokenAuthenticatorTest.php
  tests/Integration/Security/Generator/JwtTokenGeneratorTest.php
  tests/Traits/Lti1p3SecurityTestingTrait.php
  tests/Unit/Security/Generator/JwtTokenCacheIdGeneratorTest.php
Labels: Type: Security fix

#218 Release v2.0.8
  .Jenkinsfile
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  config/services.yaml
  phpunit.xml.dist
  src/Command/Cache/UserCacheWarmerCommand.php
  src/Command/GarbageCollector/AssignmentGarbageCollectorCommand.php
  src/Command/Ingester/AbstractCsvIngesterCommand.php
  src/Security/Authenticator/JwtTokenAuthenticator.php
  src/Security/Generator/JwtTokenCacheIdGenerator.php
  src/Security/Generator/JwtTokenGenerator.php
  src/Security/Verifier/JwtTokenVerifier.php
  symfony.lock
  tests/Functional/Action/Lti/UpdateLti1p3OutcomeActionTest.php
  tests/Integration/Lti/Builder/Lti1p3MessageBuilderTest.php
  tests/Integration/Security/Authenticator/JwtTokenAuthenticatorTest.php
  tests/Integration/Security/Generator/JwtTokenGeneratorTest.php
  tests/Traits/Lti1p3SecurityTestingTrait.php
  tests/Unit/Security/Generator/JwtTokenCacheIdGeneratorTest.php
Labels: Type: Release

#215 [RO-315] Added groupId to line item
  CHANGELOG.md
  config/doctrine/LineItem.orm.xml
  docs/cli-documentation.md
  docs/cli/modify-entity-line-item-change-dates-command.md
  docs/cli/modify-entity-line-item-change-status-command.md
  docs/db-uml.png
  openapi/api_v1.yml
  src/Command/Ingester/LineItemIngesterCommand.php
  src/Command/ModifyEntity/LineItem/LineItemChangeDatesCommand.php
  src/Command/ModifyEntity/LineItem/LineItemChangeStatusCommand.php
  src/Entity/LineItem.php
  src/Repository/Criteria/FindLineItemCriteria.php
  src/Repository/LineItemRepository.php
  tests/Fixtures/100usersWithAssignments.yml
  tests/Fixtures/3LineItems.yml
  tests/Functional/Action/Assignment/ListUserAssignmentsActionTest.php
  tests/Functional/Command/Ingester/AssignmentIngesterCommandTest.php
  tests/Functional/Command/Ingester/LineItemIngesterCommandTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeDatesCommandTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeStatusCommandTest.php
  tests/Unit/Entity/AssignmentTest.php
  tests/Unit/Entity/LineItemTest.php
  tests/Unit/Repository/Criteria/FindLineItemCriteriaTest.php
Labels: Type: Feature

#219 [RO-201] Line item status during ingestion
  CHANGELOG.md
  docs/cli/line-item-ingester-command.md
  src/Command/Ingester/LineItemIngesterCommand.php
  tests/Functional/Command/Ingester/LineItemIngesterCommandTest.php
Labels: Type: Feature
