Repository oat-sa/simple-roster, pull requests merged in 2021-02, with the labels that each got.

#187 Fixed lti_version LTI parameter from 1.1.1 to LTI-1p0
  CHANGELOG.md
  README.md
  docs/features/lti.md
  src/Lti/Builder/Lti1p1LaunchUrlBuilder.php
  tests/Functional/Action/Lti/GetUserAssignmentLtiLinkActionTest.php
  tests/Unit/Lti/Builder/Lti1p1LaunchUrlBuilderTest.php
Labels: Type: Bugfix

#188 Release v2.0.1
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  config/packages/security_checker.yaml
  docs/cli/lti-instance-ingester-command.md
  docs/devops-documentation.md
  docs/features/lti.md
  src/Lti/Builder/Lti1p1LaunchUrlBuilder.php
  symfony.lock
  tests/Functional/Action/Lti/GetUserAssignmentLtiLinkActionTest.php
  tests/Unit/Lti/Builder/Lti1p1LaunchUrlBuilderTest.php
Labels: Type: Release

#189 Extended devops documentation with database uml diagram
  docs/db-uml.png
  docs/devops-documentation.md
Labels: Type: Documentation

#190 [RO-210] Synchronous cache warmup fix
  CHANGELOG.md
  README.md
  composer.lock
  config/packages/docker/monolog.yaml
  phpstan.neon
  src/Action/Lti/GetUserAssignmentLtiLinkAction.php
  src/EventSubscriber/UserCacheInvalidationSubscriber.php
  src/MessageHandler/WarmUpGroupedUserCacheMessageHandler.php
  symfony.lock
  tests/Unit/MessageHandler/WarmUpGroupedUserCacheMessageHandlerTest.php
Labels: Type: Bugfix

#191 [RO-211] JWT authenticator - request support fix
  CHANGELOG.md
  src/Security/Authenticator/JwtTokenAuthenticator.php
  tests/Integration/Security/Authenticator/JwtTokenAuthenticatorTest.php
Labels: Type: Bugfix

#192 Release v2.0.2
  CHANGELOG.md
  README.md
  composer.lock
  config/packages/docker/monolog.yaml
  docs/db-uml.png
  docs/devops-documentation.md
  phpstan.neon
  src/Action/Lti/GetUserAssignmentLtiLinkAction.php
  src/EventSubscriber/UserCacheInvalidationSubscriber.php
  src/MessageHandler/WarmUpGroupedUserCacheMessageHandler.php
  src/Security/Authenticator/JwtTokenAuthenticator.php
  symfony.lock
  tests/Integration/Security/Authenticator/JwtTokenAuthenticatorTest.php
  tests/Unit/MessageHandler/WarmUpGroupedUserCacheMessageHandlerTest.php
Labels: Type: Release

#194 [RO-225] Fixed LTI 1.1 outcome signature validation logic
  CHANGELOG.md
  README.md
  src/EventSubscriber/OAuthSignatureValidationSubscriber.php
  src/Lti/Collection/UniqueLtiInstanceCollection.php
  src/Repository/LtiInstanceRepository.php
  src/Security/OAuth/OAuthContext.php
  tests/Functional/Action/Lti/UpdateLti1p1OutcomeActionTest.php
  tests/Integration/Repository/LtiInstanceRepositoryTest.php
  tests/Unit/Lti/Collection/UniqueLtiInstanceCollectionTest.php
  tests/Unit/Security/OAuth/OAuthContextTest.php
Labels: Type: Bugfix

#195 Release v2.0.3
  CHANGELOG.md
  README.md
  src/EventSubscriber/OAuthSignatureValidationSubscriber.php
  src/Lti/Collection/UniqueLtiInstanceCollection.php
  src/Repository/LtiInstanceRepository.php
  src/Security/OAuth/OAuthContext.php
  tests/Functional/Action/Lti/UpdateLti1p1OutcomeActionTest.php
  tests/Integration/Repository/LtiInstanceRepositoryTest.php
  tests/Unit/Lti/Collection/UniqueLtiInstanceCollectionTest.php
  tests/Unit/Security/OAuth/OAuthContextTest.php
Labels: Type: Release

#193 Added Psalm to CI pipeline
  .Jenkinsfile
  .env
  .gitignore
  composer.json
  composer.lock
  config/bundles.php
  config/packages/doctrine.yaml
  config/packages/psr_http_message_bridge.yaml
  docs/continuous-integration.md
  phpstan.neon
  phpunit.xml.dist
  psalm.xml.dist
  src/Action/Assignment/ListUserAssignmentsAction.php
  src/Action/Lti/GetUserAssignmentLtiLinkAction.php
  src/Command/Cache/UserCacheWarmerCommand.php
  src/Command/GarbageCollector/AssignmentGarbageCollectorCommand.php
  src/Command/Ingester/AbstractCsvIngesterCommand.php
  src/Command/ModifyEntity/LineItem/LineItemChangeDatesCommand.php
  src/EventListener/Doctrine/UserPasswordEncoderListener.php
  src/Lti/Extractor/ReplaceResultSourceIdExtractor.php
  src/MessageHandler/WarmUpGroupedUserCacheMessageHandler.php
  src/Repository/AssignmentRepository.php
  src/Repository/LineItemRepository.php
  src/Repository/LtiInstanceRepository.php
  src/Repository/NativeUserRepository.php
  src/Repository/UserRepository.php
  src/Request/ParamConverter/JwtTokenParamConverter.php
  src/Security/Handler/LogoutSuccessHandler.php
  src/Service/CompleteUserAssignmentService.php
  symfony.lock
  tests/Functional/Action/Bulk/BulkCreateUsersAssignmentsActionTest.php
  tests/Functional/Action/Bulk/BulkUpdateUsersAssignmentsStateActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p3OutcomeActionTest.php
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeDatesCommandTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeStateCommandTest.php
  tests/Integration/Lti/Responder/LtiOutcomeResponderTest.php
  tests/Integration/Repository/AssignmentRepositoryTest.php
  tests/Traits/AssignmentStatusTestingTrait.php
  tests/Unit/Bulk/Operation/BulkOperationCollectionTest.php
  tests/Unit/Lti/Responder/XmlResponseTest.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
  tests/Unit/Service/CompleteUserAssignmentServiceTest.php
  tests/Unit/Webhook/Service/UpdateLineItemsServiceTest.php
  tests/Unit/Webhook/UpdateLineItemCollectionTest.php
  tests/bootstrap.php
Labels: Type: CI

#197 Release v2.0.4
  .Jenkinsfile
  .env
  .gitignore
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  config/bundles.php
  config/packages/doctrine.yaml
  config/packages/psr_http_message_bridge.yaml
  docs/continuous-integration.md
  phpstan.neon
  phpunit.xml.dist
  psalm.xml.dist
  src/Action/Assignment/ListUserAssignmentsAction.php
  src/Action/Lti/GetUserAssignmentLtiLinkAction.php
  src/Bulk/Result/BulkResult.php
  src/Command/Cache/UserCacheWarmerCommand.php
  src/Command/GarbageCollector/AssignmentGarbageCollectorCommand.php
  src/Command/Ingester/AbstractCsvIngesterCommand.php
  src/Command/ModifyEntity/LineItem/LineItemChangeDatesCommand.php
  src/EventListener/Doctrine/UserPasswordEncoderListener.php
  src/Lti/Extractor/ReplaceResultSourceIdExtractor.php
  src/MessageHandler/WarmUpGroupedUserCacheMessageHandler.php
  src/Model/UsernameCollection.php
  src/Repository/AssignmentRepository.php
  src/Repository/LineItemRepository.php
  src/Repository/LtiInstanceRepository.php
  src/Repository/NativeUserRepository.php
  src/Repository/UserRepository.php
  src/Request/ParamConverter/JwtTokenParamConverter.php
  src/Security/Handler/LogoutSuccessHandler.php
  src/Service/Bulk/BulkCreateUsersAssignmentsService.php
  src/Service/CompleteUserAssignmentService.php
  symfony.lock
  tests/Functional/Action/Bulk/BulkCreateUsersAssignmentsActionTest.php
  tests/Functional/Action/Bulk/BulkUpdateUsersAssignmentsStateActionTest.php
  tests/Functional/Action/Lti/UpdateLti1p3OutcomeActionTest.php
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeDatesCommandTest.php
  tests/Functional/Command/ModifyEntity/LineItem/LineItemChangeStateCommandTest.php
  tests/Integration/Lti/Responder/LtiOutcomeResponderTest.php
  tests/Integration/Repository/AssignmentRepositoryTest.php
  tests/Traits/AssignmentStatusTestingTrait.php
  tests/Unit/Bulk/Operation/BulkOperationCollectionTest.php
  tests/Unit/Bulk/Result/BulkResultTest.php
  tests/Unit/Lti/Responder/XmlResponseTest.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
  tests/Unit/Service/Bulk/BulkCreateUsersAssignmentsServiceTest.php
  tests/Unit/Service/CompleteUserAssignmentServiceTest.php
  tests/Unit/Webhook/Service/UpdateLineItemsServiceTest.php
  tests/Unit/Webhook/UpdateLineItemCollectionTest.php
  tests/bootstrap.php
Labels: Type: Release
