Repository oat-sa/simple-roster, pull requests merged in 2021-01, with the labels that each got.

#183 [RO-46] JWT authentication flow enhancements
  .env
  .env.docker
  .env.test
  .gitignore
  composer.json
  composer.lock
  config/packages/monolog.yaml
  config/packages/security.yaml
  config/routes.yaml
  config/secrets/docker/.gitkeep
  config/services.yaml
  config/services_test.yaml
  docs/blackfire.md
  docs/continuous-integration.md
  docs/devops-documentation.md
  docs/docker-development.md
  docs/local-development.md
  openapi/api_v1.yml
  phpstan.neon
  src/Action/Security/RefreshAccessTokenAction.php
  src/Request/ParamConverter/JwtTokenParamConverter.php
  src/Security/Authenticator/JwtTokenAuthenticator.php
  src/Security/Generator/JwtTokenCacheIdGenerator.php
  src/Security/Generator/JwtTokenGenerator.php
  src/Security/Handler/AuthenticationSuccessHandler.php
  src/Security/Handler/LogoutSuccessHandler.php
  src/Security/Verifier/JwtTokenVerifier.php
  src/Service/JWT/TokenGenerator.php
  src/Service/JWT/TokenStorage.php
  tests/Functional/Action/Assignment/ListUserAssignmentsActionTest.php
  tests/Functional/Action/Lti/GetUserAssignmentLtiLinkActionTest.php
  tests/Functional/Action/Security/LoginActionTest.php
  tests/Functional/Action/Security/LogoutActionTest.php
  tests/Functional/Action/Security/RefreshAccessTokenActionTest.php
  tests/Integration/Security/Authenticator/JwtTokenAuthenticatorTest.php
  tests/Integration/Security/Generator/JwtTokenGeneratorTest.php
  tests/Integration/Security/Verifier/JwtTokenVerifierTest.php
  tests/Traits/UserAuthenticatorTrait.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
  tests/Unit/Security/Authenticator/JwtTokenAuthenticatorTest.php
  tests/Unit/Security/Generator/JwtTokenCacheIdGeneratorTest.php
  tests/Unit/Webhook/UpdateLineItemCollectionTest.php
Labels: Type: Enhancement, Type: Feature

#182 [RO-80] Added basic auth for webhook endpoint
  .env
  .env.docker
  .env.test
  CHANGELOG.md
  config/packages/security.yaml
  docs/devops-documentation.md
  docs/features/update-line-items-webhook.md
  openapi/api_v1.yml
  tests/Functional/Action/WebHook/UpdateLineItemsWebhookActionTest.php
Labels: Type: Feature

#175 Replace Debian by Alpine Image
  .Jenkinsfile
  docker/jenkins/Dockerfile
  docker/phpfpm/Dockerfile
  docs/docker-development.md
Labels: Type: CI, Type: Technical Debt

#176 [RO-46] Replace PHPSESSID with JWT
  .env
  .env.docker
  .env.test
  .gitignore
  CHANGELOG.md
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/packages/monolog.yaml
  config/packages/security.yaml
  config/routes.yaml
  config/secrets/dev/.gitkeep
  config/secrets/docker/.gitkeep
  config/secrets/prod/.gitkeep
  config/secrets/test/jwt_private.pem
  config/secrets/test/jwt_public.pem
  config/services.yaml
  config/services_test.yaml
  docker-compose.yml
  docs/blackfire.md
  docs/continuous-integration.md
  docs/devops-documentation.md
  docs/docker-development.md
  docs/local-development.md
  openapi/api_v1.yml
  phpcs.xml
  src/Action/Security/RefreshAccessTokenAction.php
  src/Entity/User.php
  src/Logger/UserRequestLogProcessor.php
  src/Request/ParamConverter/JwtTokenParamConverter.php
  src/Security/Authenticator/JwtTokenAuthenticator.php
  src/Security/Exception/TokenExtractionException.php
  src/Security/Generator/JwtTokenCacheIdGenerator.php
  src/Security/Generator/JwtTokenGenerator.php
  src/Security/Handler/AuthenticationSuccessHandler.php
  src/Security/Handler/LogoutSuccessHandler.php
  src/Security/TokenExtractor/AuthorizationHeaderTokenExtractor.php
  src/Security/Verifier/JwtTokenVerifier.php
  src/Service/Bulk/BulkUpdateUsersAssignmentsStateService.php
  tests/Functional/Action/Assignment/ListUserAssignmentsActionTest.php
  tests/Functional/Action/Lti/GetUserAssignmentLtiLinkActionTest.php
  tests/Functional/Action/Security/LoginActionTest.php
  tests/Functional/Action/Security/LogoutActionTest.php
  tests/Functional/Action/Security/RefreshAccessTokenActionTest.php
  tests/Integration/Security/Authenticator/JwtTokenAuthenticatorTest.php
  tests/Integration/Security/Generator/JwtTokenGeneratorTest.php
  tests/Integration/Security/Verifier/JwtTokenVerifierTest.php
  tests/Traits/UserAuthenticatorTrait.php
  tests/Unit/Logger/UserRequestLogProcessorTest.php
  tests/Unit/Request/ParamConverter/UpdateLineItemWebHookParamConverterTest.php
  tests/Unit/Security/Generator/JwtTokenCacheIdGeneratorTest.php
  tests/Unit/Security/TokenExtractor/AuthorizationHeaderTokenExtractorTest.php
  tests/Unit/Webhook/UpdateLineItemCollectionTest.php
Labels: Type: Feature, Type: Technical Debt

#184 [RO-69] Move healthcheck endpoint to API root
  CHANGELOG.md
  README.md
  composer.lock
  config/packages/security.yaml
  config/routes.yaml
  docs/cli-documentation.md
  docs/devops-documentation.md
  docs/features/lti.md
  openapi/api_v1.yml
  tests/Functional/Action/HealthCheck/HealthCheckActionTest.php
Labels: Type: Documentation, Type: Feature
